FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar


ARG DATASOURCE_URL
ARG DATASOURCE_USERNAME
ARG DATASOURCE_PASSWORD

ENV SPRING_DATASOURCE_URL=$DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$DATASOURCE_PASSWORD

ENTRYPOINT ["java","-jar","/app.jar"]