name: Devfest Demo

on:
  workflow_dispatch:
  push:
    branches:    
      - '**'

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      #- name: Maven Verify
      #  run: mvn -B clean verify -DskipTests
      - name: Copy jar artifact
        run: mkdir artifact && cp target/*.jar artifact
      - uses: actions/upload-artifact@v2
        with:
          name: my-java-artifact
          path: application/artifact

          


  build-and-push-image:
    environment: sandbox
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: package
    
    defaults:
      run:
        # Comportement étrange:  Malgré la mention ici du working directory certaines steps ne le prennent pas en compte
        working-directory: application
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-java-artifact
          path: application/target

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        env:
          REPO: ${{ secrets.DOCKER_REPO }}

        with:
          context: ./application
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}"
            "DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME}}"
            "DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD}}"
